config/routes.rb
Rails.application.routes.draw do

  root to: 'health_centres#index'

  get 'points', to: 'health_centres#points'
  get 'procedures/:id', to: 'health_centres#procedures'
  get 'specialties/:id', to: 'health_centres#specialties'
  get 'procedures_specialties/:id', to: 'health_centres#procedures_specialties'
  get 'health_centre_specialty/:hc_id/:spec_id', to: 'health_centres#health_centre_specialty'
  get 'specialties_count', to: 'health_centres#specialties_count'
  get '/specialties_procedure_distance_average', to: 'health_centres#specialties_procedure_distance_average'
  get 'distances/:id', to: 'health_centres#distances'
  get '/rank_health_centres', to: 'health_centres#rank_health_centres'

  get 'dashboard', to: 'dashboard#index'
  get 'specialties', to: 'specialties#index'
  get 'health_centre_filter', to: 'health_centre_filter#index'
  get 'health_centre_filter/:health_centre_id/:specialty_id', to: 'health_centre_filter#filter_health_centres'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/health_centre.rb
class HealthCentre < ApplicationRecord
  has_many :procedures, foreign_key: :cnes_id, primary_key: :cnes
  has_many :health_centre_specialties
  has_many :specialties, through: :health_centre_specialties
  has_many :health_centre_types
  has_many :types, through: :health_centre_types
end

app/models/health_centre_specialty.rb
class HealthCentreSpecialty < ApplicationRecord
  belongs_to :health_centre
  belongs_to :specialty
end

app/models/health_centre_type.rb
class HealthCentreType < ApplicationRecord
  belongs_to :health_centre
  belongs_to :type
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :specialty
  belongs_to :cnes, :class_name => 'HealthCentre', foreign_key: :cnes_id, primary_key: :cnes
  acts_as_mappable lat_column_name: :lat, lng_column_name: :long

  def calculate_distance
    health_centre = self.cnes
    self.distance_to([health_centre.lat, health_centre.long]) if health_centre
  end
end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_many :procedures
  has_many :health_centre_specialties
  has_many :health_centres, through: :health_centre_specialties
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :health_centre_types
  has_many :health_centres, through: :health_centre_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  # get '/'
  def index
  end
end

app/controllers/health_centre_filter_controller.rb
class HealthCentreFilterController < ApplicationController
  # GET /
  def index
    @health_centres = HealthCentre.all
    @health_centres = @health_centres.sort{|h1, h2|  h1.name.downcase <=> h2.name.downcase }
  end

  # GET health_centre_filter/:health_centre_id/:specialty_id
  def filter_health_centres
    selected_health_centre = HealthCentre.find params[:health_centre_id].to_i
    types = selected_health_centre.types
    @set = Set.new

    types.each do | type|
      @set << type.health_centres.select {|h| h if h.specialty_ids.include?(params[:specialty_id].to_i)}
    end

    render json: @set.to_a[0]
  end
end

app/controllers/health_centres_controller.rb
class HealthCentresController < ApplicationController
    # GET /
    def index
        @health_centres = HealthCentre.all
    end

    # GET /points
    def points
        @health_centres_points = HealthCentre.all
        render json: @health_centres_points
    end

    # GET /procedures/:id
    def procedures
        @health_centre = HealthCentre.find_by(id: params[:id])
        render json: @health_centre.procedures
    end

    # GET /specialties/:id
    def specialties
        health_centre = HealthCentre.find_by(id: params[:id])
        procedures = health_centre.procedures
        result = {}

        procedures.each do |procedure|
           specialty_name = procedure.specialty.name
           if result.keys.include?(specialty_name)
              result[specialty_name] += 1
           else
              result[specialty_name] = 1
           end
        end
        render json: result
    end

    # GET /specialties_count
    def specialties_count
        result = {}

        for spec_id in 1..9
            procedures = Procedure.where(specialty_id: spec_id)
            result[Specialty.find_by(id: spec_id).name] = procedures.count
        end

        render json: result
    end

    # GET /specialties_procedure_distance_average
    def specialties_procedure_distance_average
      result = {}

      for spec_id in 1..9
        distance_average = (Procedure.where(specialty_id: spec_id).average(:distance) or 0.0)
        result[ Specialty.find(spec_id).name] = distance_average.round(2)
      end

      render json: result
    end

    # GET /rank_health_centres
    def rank_health_centres
      health_centres = HealthCentre.all.to_a
      health_centres.sort! { |first, second|  first.procedures.count <=> second.procedures.count }
      result = {}

      health_centres.reverse.each_with_index do |health_centre, index|
        break if index == 10
        result[health_centre.name] = health_centre.procedures.count
      end
      render json: result
    end

    # GET /procedures_specialties/:id
    def procedures_specialties
        procedures = Procedure.where(specialty_id: params[:id])
        render json: procedures
    end

    # GET /health_centre_specialty/:hc_id/:spec_id
    def health_centre_specialty
        health_centre = HealthCentre.find_by(id: params[:hc_id])
        procedures = health_centre.procedures

        procedures_specialties = procedures.where(specialty_id: params[:spec_id])
        render json: procedures_specialties
    end

    # GET /distances/:id
    def distances
        health_centre = HealthCentre.find_by(id: params[:id])
        procedures = health_centre.procedures

        distances = Hash.new(0)
        distances_by_specialty = {}

        for i in 1..9
            distances_by_specialty[i] = Hash.new(0)
        end

        labels = ['1', '5', '10', '10+']

        procedures.each do |procedure|
            specialty = procedure.specialty.id

            if procedure.distance <= 1
                distances[labels[0]] += 1
                distances_by_specialty[specialty][labels[0]] += 1
            elsif procedure.distance <= 5
                distances[labels[1]] += 1
                distances_by_specialty[specialty][labels[1]] += 1
            elsif procedure.distance <= 10
                distances[labels[2]] += 1
                distances_by_specialty[specialty][labels[2]] += 1
            else
                distances[labels[3]] += 1
                distances_by_specialty[specialty][labels[3]] += 1
            end
        end

        total_info = {'distances': distances, 'specialty': distances_by_specialty}

        render json: total_info
    end

end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController

  # get '/'
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/health_centre_filter_helper.rb
module HealthCentreFilterHelper
end

app/helpers/health_centre_helper.rb
module HealthCentreHelper
end

app/views/dashboard/index.html.erb
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">

<div class="w3-container">
  <div class="w3-card-4" >
    <header class="w3-container w3-light-grey">
      <h1><center>Dados Gerais<center></h1>
    </header>

    <div class="w3-container">
      <div class='col-md-6'>
        <table class='health_centres_rank table table-sm table-inverse'>
           <caption><center>Ranking de hospitais que realizam mais procedimentos<center></caption>
           <thead>
            <tr>
              <th>#</th>
              <th>Hospital</th>
              <th>Nº de Procedimentos</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
     </div>
      <div class='col-md-6'>
        <div id='procedure_by_date' style='width: 600px; height: 450px'></div>
      </div>
    </div>

  </div>
</div>
<div class="w3-container">
  <div class="w3-card-4" >
    <header class="w3-container w3-light-grey">
      <h1><center>Especialidades<center></h1>
    </header>
    <div class="w3-container">
     <div class='row'>
       <div class='col-md-6 col-md-offset-2'>
        <div id="chart_specialties" style="width: 900px; height: 450px;"></div>
       </div>
     </div>
     <div class='row'>
       <div class='col-md-6'>
        <div id="chart_spec_distance_average"  style="width: 600px; height: 400px;"></div>
       </div>
       <div class='col-md-6'>
        <div id="chart_spec_time_average"  style="width: 600px; height: 400px;"></div>
       </div>
     </div>
    </div>
  </div>
</div>

<div class="w3-container">
  <div class="w3-card-4" >
    <header class="w3-container w3-light-grey">
      <h1><center>Distância Média Percorrida por Pacientes<center></h1>
    </header>
    <div class="w3-container">

        <div class='row'>
          <div class='col-md-4'>
            <div id="chart_cirurgia" style="width: 400px; height: 400px;"></div>
          </div>
          <div class='col-md-4'>
            <div id="chart_obstetrecia"  style="width: 400px; height: 400px;"></div>
          </div>
          <div class='col-md-4'>
            <div id="chart_clinica_medica" style="width: 400px; height: 400px;"></div>
          </div>
        </div>

        <div class='row'>
          <div class='col-md-4'>
            <div id="chart_pacientes" style="width: 400px; height: 400px;"></div>
          </div>
          <div class='col-md-4'>
            <div id="chart_psiquiatria"  style="width: 400px; height: 400px;"></div>
          </div>
          <div class='col-md-4'>
            <div id="chart_tisiologia" style="width: 400px; height: 400px;"></div>
          </div>
        </div>

        <div class='row'>
          <div class='col-md-4'>
            <div id="chart_pediatria"  style="width: 400px; height: 400px;"></div>
          </div>
          <div class='col-md-4'>
            <div id="chart_reabilitacao" style="width: 400px; height: 400px;"></div>
          </div>
          <div class='col-md-4'>
            <div id="chart_psiquiatria_dia" style="width: 400px; height: 400px;"></div>
          </div>
        </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="help-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Ajuda</h4>
      </div>
      <div class="modal-body">
          <p>Aqui é possível visualizar métricas relacionadas aos estabelecimentos de saúde da cidade de São Paulo.
             São apresentadas métricas por especialidade envolvendo distância percorrida e tempo gasto pelos
             pacientes na realização de seus procedimentos.
          </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(init_dashboard_chart);
  $(document).ready(update_rank);
  $(document).ready(init_specialties_chart);
</script>

app/views/health_centre_filter/index.html.erb
<div class='col-md-8 col-sm-8 affix'>
  <div id='specialty-map-filter'> </div>
  <div id="legend"><h3>Distância</h3></div>
</div>

  <div class='col-md-8'>
  </div>

  <div class='col-md-4 col-sm-4'>
    <div class="panel-group" id="accordion">
    <% for health_centre in @health_centres %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#<%= health_centre.id %>">
            <%= health_centre.name.titleize %></a>
          </h4>
        </div>
        <div id="<%= health_centre.id %>" class="panel-collapse collapse">
          <ul class="list-group">
            <% for specialty in health_centre.specialties %>
            <li class="list-group-item"   onclick='filter_by( <%= health_centre.id %> , <%= specialty.id %>)'><%= specialty.name %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    </div>
  </div>

  <div class='col-md-8 col-sm-8 affix' style='margin-top: 500px'>
  </div>

<!-- Modal -->
<div id="help-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Ajuda</h4>
      </div>
      <div class="modal-body">
          <p>A lista a direita apresenta os estabelecimentos de saúde de São Paulo. Ao clicar em algum estabelecimento, suas especialidades são
             listadas abaixo.
          </p>
          <p>Ao clicar em alguma especialidade relacionada a algum estabelecimento, será mostrado no mapa o estabelecimento e a localidade de
             onde os pacientes vieram para realizar os procedimentos. Além disso, para fins comparativos, serão apresentados os outros
             estabelecimentos de saúde que atendem a mesma especialidade e são do mesmo porte do estabelecimento selecionado.
          </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(initialize_health_centre_filter)
</script>

app/views/health_centres/index.html.erb
<div class='map-wrapper col-md-9 col-sm-9'>
  <div id='map'></div>
</div>

<div class='col-sm-3 col-md-3 pull-right '>
  <div class='row'>
    <div id='general-right-graph'></div>
    <div id="labelOverlay">
        <p class="n_procedures"></p>
        <p class="atendimentos"></p>
    </div>
  </div>

  <div class='row'>
    <div id='distance-legend'>
        <div class='item'> <div class="color lt-1km"></div><p class="text">&lt; 1 km</p> </div>
        <div class='item'> <div class="color lg-1km-lt-5"></div><p class="text">&gt; 1 km e &lt; 5 km</p> </div>
        <div class='item'> <div class="color lg-5km-lt-10"></div><p class="text">&gt; 5 km e &lt; 10 km</p> </div>
        <div class='item'> <div class="color lg-10km"></div><p class="text">&gt; 10 km</p> </div>
    </div>
  </div>

  <div class='row'>
    <div id="metric-board">
      <h1 id='value'></h1>
      <p  id='text'>Número de procedimentos suportados em centros de saúde mais próximos do que o local onde foram realizados.</p>
    </div>
   </div>

</div>

<div class='col-md-9 col-sm-9 graphs-bottom'>
   <div class='col-md-6' id='bt-graph1'></div>
   <div class='col-md-6' id='bt-graph2'></div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Dados</h4>
      </div>
      <div class="modal-body">
          <div id="chart_div"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="help-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Ajuda</h4>
      </div>
      <div class="modal-body">
          <p>No mapa pode-se encontrar todos os estabelecimentos de saúde de São Paulo. Clicando em algum deles é possível visualizar informações
             referentes a localização de pacientes que realizaram procedimentos naquele estabelecimento, e visualizar dados de procedimentos por
             especialidades.
          </p>
          <p>Ao redor do mapa são apresentados gráficos de procedimentos por especialidades na cidade de São Paulo. Uma métrica de quantos procedimentos poderiam ter
             sido realizados mais próximo da localidade dos pacientes é apresentada.
          </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

<div id="legend"><h3>Distância</h3></div>

<script>
  $(document).ready(initialize)
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthSmartCity</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!-- Google MAPS API -->
   <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyC3nPH6fHf4j-Dmt_e9Z-5cvlJEvVDi6Ss" %>
  </head>

  <body>
      <div class="navbar navbar-inverse navbar-fixed-top">
          <nav>
            <ul class="nav navbar-nav navbar-left">
              <li class='nav-item <%= 'active' if controller_name == 'health_centres'  %>  '> <%= link_to "Início", root_path, class: 'nav-link' %></li>
              <li class='nav-item <%= 'active' if controller_name == 'health_centre_filter'  %>' > <%= link_to "Estabelecimentos", health_centre_filter_path, class: 'nav-link' %></li>
              <li class='nav-item <%= 'active' if controller_name == 'dashboard'  %>'> <%= link_to "Métricas", dashboard_path, class: 'nav-link' %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class='nav-item'><a href='#' class='nav-link glyphicon glyphicon-question-sign' data-toggle="modal" onclick="update_chart()" data-target="#help-modal"></a></li>
            </ul>
          </nav>
      </div>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>